EaglePhntm/NTFvsAlien

code/modules/mob/living/carbon/xenomorph/xenomorph.dm

Adds text on inspect for disconnected / ghosted xenomorphs.
Humans have it, why not xenos.
:cl: Casper
add: Adds ghosted / disconnected examine text to xenos.
/:cl:

Feature: Examining a xeno now shows if they are disconnected / ghosted.

---

code/datums/jobs/job/sonsofmars.dm
code/modules/reqs/supply.dm

Hey Vide. Did a bit of pondering though it's taken a while to get along to it. But with how little players the SOM usually get, perhaps allowing certain squad roles to use req would be a nice bit of QOL.
In this PR, those roles are the SOM squad engineer and squad leader.
With the lesser numbers SOM typically has, I think it'd be convenient to make it so atleast 1 or two squad roles can get to it in an emergency.

Adjusts SOM req access.

---

code/datums/emotes.dm
code/modules/mob/emote.dm
code/modules/mob/say.dm

- you can now use bold/italics/underlines for emotes
- removed that thing that adds punctuation because it doesn't work with emotes/subtler well. it's not hard to add a period
you can now bold, italicize and use underlines for emotes.
punctuation thing got removed because having a period added at the end of your statement when subtlering/emoting is goofy. it's also not really that hard to just punctuate yourself.
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed …

text emphasis for emotes.

---

code/controllers/subsystem/vote.dm

Fixes a bug that made successful restart votes with no active admins run into a runtime error when trying to restart the server, resulting in it not restarting.
Restart votes are useful and should work as intended.
:cl:
fix: Fixed restart votes never actually restarting the server.
/:cl:

Makes restart votes work

---

code/game/objects/machinery/cryopod.dm

Fixed an error that caused SSD players put in hypersleep to not be deleted.
Not stuck with ssd players lying around.  
:cl:
fix: Putting SSD players in hypersleep works again
/:cl:

Hypersleep fix

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Cuts egg laying cooldown from 12 seconds to 8.
Eggs are fun and iconic.
:cl:
balance: Xeno egg laying cooldown reduced from 12 seconds to 8 seconds
/:cl:

Cut egg laying cooldown from 12 seconds to 2

---

code/modules/mob/dead/observer/observer.dm

Fixes observer time out turning you back into an observer but invisible immediately after sending you to the lobby
Invisible observers are weird and unintended
:cl:
fix: fixed observer time out glitchiness
/:cl:

Fixes observer time out

---

code/datums/datacore.dm

Lets ghosts/lobbied players see all factions on manifest
Lets people see how many people are actually active before joining and helps them decide which faction to join.
:cl:
add: Let ghosts and people in the lobby see all factions in the game manifest.
/:cl:

Lets ghosts/lobbied players see all factions on manifest

---

ntf_modular/code/datums/sexcon/sexcon_helpers.dm

Fixed larva sometimes being born to the wrong hive and not emerging from the right hole.
Corrupted xenos don't have to worry about creating enemy larva.
:cl:
fix: Fixed larva sometimes being born to the wrong hive and not emerging from the right hole.
/:cl:

Fixed larva sometimes being born to the wrong hive

---

code/datums/gamemodes/extendedsurv.dm
config/modes.txt
tgmc.dme

Since there seem to have been some problems with survival recently, I thought this would be a fun and easy-to-code alternative.  Adds a variant of Extended in which survivor slots are unlimited and non-survivor slots are very limited. 
Should help spice things up, give more variety of gamemodes.
:cl:
add: Added Survivor-Heavy Extended gamemode, an extended variant in which survivor slots are unlimited and non-survivor slots are very limited.
/:cl:

Adds Survivor-Heavy Extended variant gamemode

---

_maps/lv624small.json
_maps/map_files/LV624/LV624.dmm
_maps/map_files/LV624Small/LV624Small.dmm
config/maps.txt

Adds lv624small, a copy of lv624 without the huge marine base taking up the bottom half of the map and making the minimap too big for the screen.  Also some minor mapping fixes to lv624.
Should be more fun to play on.
:cl:
add: New map: LV624Small, a copy of LV624 without the huge marine base taking up the bottom half of the map.
/:cl:

Adds lv624small

---

code/modules/power/groundmap_geothermal.dm

Fixes incorruptible generators starting corrupted.
If they're incorruptible it doesn't make sense for them to start corrupted.
:cl:
fix: Fixed incorruptible generators starting out corrupted.
/:cl:

Fix incorruptible generators starting corrupted

---

ntf_modular/code/modules/mob/ooc_notes.dm

Fixes ooc notes sometimes not being viewable
It's good for people to be able to see each other's ooc notes.

Fix ooc notes sometimes not being viewable

---

code/modules/reagents/chemistry/reagents/toxin.dm

Make neurotoxin stun instead of killing.
Gives xenos more of a chance to get caps.  Makes it less redundant with acid spit.
:cl:
balance: Neurotoxin now stuns people instead of killing them.
/:cl:

Make neurotoxin stun instead of killing

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm

Gives queen and spitter neuro spit
Xenos that have acid spit should have neuro spit too.  Gives them a way to use spit to capture.
:cl:
balance: Queen and spitter now have neuro spit.
/:cl:

Gives queen and spitter neuro spit

---

code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm

Makes Defiler's Reagent Slash, Sentinel's Toxic Slash, and Hunter's Sneak Attack work on disarms too.  (The last was already mostly coded in, just the signal wasn't being sent.)
Gives xenos better nonlethal options to promote captures.
:cl:
add: Defiler's Reagent Slash, Sentinel's Toxic Slash, and Hunter's Sneak Attack now work on disarms too.
/:cl:

Makes some xeno slash effects work with disarms

---

code/modules/projectiles/ammo_types/shotgun_ammo.dm

Fixes six gauge "barrikada" slugs to make sure they actually apply the intended knockback, stagger and stun effects. The code read as "/datum/ammo/bullet/shotgun/barrikada/on_hit_mob(mob/target_mob, obj/projectile/proj)" as opposed to the expected "/datum/ammo/bullet/shotgun/barrikada_slug/on_hit_mob(mob/target_mob, obj/projectile/proj)" and as such didn't apply the expected stagger effect. My experiences in game effect this.
Unfortunately I could not fully test this locally however, as spawning any xenos in a local game causes a code error and valhalla is not enabled. If this fix works, it should be apparent and testable in the live game.
This fix _also_ effects the ML-101 shotgun due to them sharing the same ammo type.
Restores intended effects.
:cl:
fix: Fixed 6 gauge slugs not …

SH-23 Slug Fix

---

code/modules/projectiles/ammo_types/shotgun_ammo.dm

Initial testing before addition of the SH-23 did point to it being potentially weaker than expected due to the lack of attachments and very slow rechamber speed, more akin to a sniper without the advantages of aimmode as opposed to a traditional shotgun.  Think martini henry. This seems to have been correct given my current experiences ingame.
As such I have buffed every ammunition type slightly, with emphasis on the flechettes and buckshot ammotypes. This is due to the fact that flechettes and buckshot travel very slowly across the screen, lacking the raw speed found from the SH-35 with barrel charger or extended barrel. Flechettes in particular are slow enough that I have witnessed people stepping out of the way of the bullets before they land with ease.
Slugs: 5 more damage and sunder, …

SH-23 Overall Buffs

---

code/modules/mob/living/carbon/xenomorph/attack_alien.dm

Currently xenos disarms are limited to raising people's stamina loss to maxHealth, which is half of the absolute limit on it  which most other sources of stamina damage can raise it to.  This makes it work the same as any other form of stamina damage, meaning xenos can keep disarming knocked down people to raise their stamina damage to the true limit, keeping them down for longer.
It's kind of weird for disarms to be limited like this.  And this will make it easier for xenos to keep people down in nests and stuff.
:cl:
balance: Xenos can now keep people down for longer by disarming them more after they've been knocked down
/:cl:

Lets xenos do more stamina damage than the minimum to knock someone down

---

code/modules/mob/new_player/new_player.dm

When someone joins as a ghost from the lobby, admins get a notification that says "The mob joined as a ghost."  Often literally that, without the actual name or key of the ghost, just calling them "The mob".  This makes it include the name and key of the ghost.
Current message is nearly useless, improved one might be useful.

Makes "joined as a ghost" notifications more useful

---

code/game/objects/items/radio/headset.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Stops facehuggers removing headsets.  Instead, facehuggers, devouring, and xeno disarm knockdowns all disable a headset's location marker for 40 seconds.
Facehuggers removing headsets made it too easy for headsets and bodies to get lost.  This avoids that while still helping xenos get away with kidnappings.
:cl:
del: Facehuggers no longer remove headsets
add: Facehuggers, devouring, and xeno disarm knockdowns all disable a headset's location marker for 40 seconds.
/:cl:

locator disabling

---

code/game/objects/items/implants/implant_items.dm
code/game/objects/items/weapons/misc.dm
code/game/objects/items/weapons/swords.dm
code/modules/clothing/clothing.dm
code/modules/clothing/modular_armor/modular.dm

buffs the knight modules
also buffs a few melee weapons that aren't too used right now
variety. magni's kinda lame right now, you give up guns and grenades for 15 armor and some really gimmicky melee skills.
:cl:
- armblade implant moved up to 75 force (it's just machete tier)
- powerfist now scales with unarmed damage
- rownin can now slot magni
- magni now gives a +1 to melee related stats + stam
- sword's dash range and speed now scale off of your actual movespeed. if sprinting with heavy armor, you'll move 3 tiles. if using rownin and sprinting, 4 tiles. if using sandev, sprinting, and rownin, you'll probably hit like 6-7 tiles idk
/:cl:

melee changes/magni buffs

---

code/controllers/configuration/entries/general.dm
code/controllers/subsystem/vote.dm
config/config.txt
tgui/packages/tgui/interfaces/Vote.jsx

Adds end round votes, which when passed end the round and restart.  Unlike restart votes, they do not skip EORD or mode/map votes.
Comments in restart vote code indicate it's meant for when things are lagging severely so the server needs to be restarted as soon as possible.  But it's also useful to have a way to restart the server by vote when people just want a new mode or map.
:cl:
add: End round votes now exist, like restart votes but they do not skip mode/map votes.
/:cl:

Adds end round votes

---

tgui/packages/tgui-panel/chat/constants.ts

Fix looc messages being sorted into chat tabs with ooc enabled rather than ones with looc enabled.
Makes the looc checkbox actually do something.
:cl:
fix: Fix looc messages being sorted into chat tabs with ooc enabled rather than ones with looc enabled.
/:cl:

fix looc chat tab sorting

---

code/game/objects/effects/landmarks/corpsespawner.dm

Makes corpses spawners that spawn corpses that are obviously killed by xenos (chestbursted, cocooned or headbitten) instead spawn nothing.
They make xenos seem a lot more genocidal than they actually are in our lore.  And they're not used for much, even though they can be useful in theory most people don't bother collecting them.
:cl:
del: Removed most roundstart corpses.
/:cl:

Disables most corpse spawners

---

code/datums/quick_load_beginners.dm
code/datums/quick_load_outfits.dm
code/datums/quick_load_robots.dm
code/game/objects/machinery/vending/beginner_vendor.dm

Fixes squad marine quick-equip loadouts being unusable
They're useful and should be usable
:cl:
/:cl:

Fixes squad marine quick-equip loadouts

---

code/game/verbs/ooc.dm

Stops people seeing loocs from other z levels
Seeing loocs from unrelated z-levels is weird and confusing.
:cl:
fix: LOOCs are now only visible on the same z-level, instead of being limited by x and y coordinates only.
/:cl:

fixes cross-z-level loocs

---

code/datums/status_effects/xeno_buffs.dm

:cl:
add: Baton pass now supports humans
tweak: Baton pass will no longer apply full effects if it somehow applies to a humanoid mob and passes the isxeno() check.
/:cl:

Baton Pass compatability pass

---

code/modules/mob/new_player/new_player.dm

Fixes observe disable warning not showing up.  Also makes it harder to miss.
Helps people know it's not just a bug that observe doesn't work.
:cl:
/:cl:

Fixes observe disable warning not showing up

---

config/maps.txt

Low pop, not likely to get 30 players so this map will almost never even show up
(Might need to be changed on the hostbox as well, forgot how this works with the config)
The xenos demand a beach episode smh
:cl:
code: decreased minplayers from 40 to 1 on riptide
/:cl:

Removes pop requirement from riptide

---

code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm

Fixes Primordial Hivelord not being able to devour. 
Fixes Widow Secrete Resin menu having wrong icons.
Fixes Widows having two copies of the button to change pheromones.
Convenience
:cl:
fix: Fixed Primordial Hivelord not being able to devour. 
fix: Fixed Widow Secrete Resin menu having wrong icons.
fix: Fixed Widows having two copies of the button to change pheromones.
/:cl:

Xeno Ability Fixes

---

_maps/map_files/antagmap/antagmap.dmm

Fix NTC field commander spawning in SOM field commander's room on their ship.
It's a bit awkward when the NTC field commander spawns in the the middle of the opposing side's ship.
:cl:
fix: Fixed NTC field commander spawning in SOM ship
/:cl:

Fix NTC field commander spawning in SOM ship

---

_maps/map_files/NTC_Nine_Tailed_Fox/NTC_Nine_Tailed_Fox.dmm
_maps/map_files/antagmap/antagmap.dmm
code/game/objects/items/cards_ids.dm

Maps in a spare NTC commander's ID on the NTC ship and a spare SOM commander's ID on the SOM ship
Lets people operate req and the tadpole without officers available.
:cl:
add: Added a spare NTC commander's ID on the NTC ship and a spare SOM commander's ID on the SOM ship
/:cl:

Gives both sides spare IDs

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Makes Xenos with their spit abilities selected no longer spit on shift-left click.  Instead alt-left click now works.  Also right click and middle click continue to work.
Avoids accidental spitting when trying to examine people.
:cl:
add:  Xenos with their spit abilities selected no longer spit on shift-left click.  Instead alt-left click now works.  Also right click and middle click continue to work.
/:cl:

Changes xeno spit controls to reduce accidents

---

code/game/objects/effects/overlays.dm
code/game/objects/items/explosives/grenades/flares.dm
code/modules/condor/cas_shuttle.dm

CAS weapons no longer fire on right-click, shift-left click, or alt-left click.  Middle click and unmodified left-click continue to work. Also fixes cas flares breaking when varedited to last longer.
Reduces accidental discharges when trying to examine things
:cl:
add: CAS weapons no longer fire on right-click, shift-left click, or alt-left click.  Middle click and unmodified left-click continue to work.
/:cl:

Adjusts CAS controls to reduce accidents.

---

code/game/objects/machinery/vending/quick_vendor.dm
code/game/objects/machinery/vending/som_vending.dm
code/modules/clothing/head/helmet.dm

what does this do?
adds the v-35 loadout from my previous pr to vendors, one of the maintainers changed it before it was merged but forgot to do that part,
adds the m10 marine helmet to som vendors
why?
the v-35 loadout will function as intended now,
the m10 helmet is there so som can actually use some of the helmet attachments from req such as the cheaper, battery powered night vision goggles that none of their helmets can accomodate

fix v-35 loadout, add marine helmet to som

---

code/datums/jobs/job/clf.dm
code/datums/jobs/job/icc_squad.dm
code/datums/jobs/job/sons_of_mars_shipside.dm
code/modules/clothing/under/marine_uniform.dm

Adds medical tweezers to the CLF medic, ICC medic and shuffles around the lemoline + advanced tweezer spawns for the SOM CMO and MD (SOM MD now gets a surgery pouch and medkit pouch roundstart). ICC medic also gets a white webbing roundstart containing a medevac stretcher, roller bed, stasis bag, nanoblood hypo, oxy hypo and a medevac beacon in-hand.
Please notify me if there are any other medical roles that don't get tweezers.
Medical tweezers are a fairly important item for medic roles to have.
:cl:
add: ICC and CLF medics now spawn with tweezers
add: ICC medics now spawn with a white webbing, medevac and misc medical equipment
add: SOM MDs now spawn with appropriate pouches
/:cl:

gives tweezers to medical roles

---

code/game/objects/items/stacks/tiles/tile_types.dm
code/game/turfs/floor.dm

Currently in-game when you crowbar a tile and place it back down, you get the default turf type instead of what it used to be.
This fixes/changes it so that when a tile is crowbarred, that its floor type (i.e. what it looks like) is preserved - the way this is implemented, you can mix metal floor tiles of different styles to make more of them (i.e. the same way it functions on CM).
I considered adding a tile painter but am unsure if there's any actual demand for this or need.
it's a fix; lets you keep the look of a room after crowbarring tiles up and putting them back down; lets you change how rooms look
:cl:
fix: crowbarred floor tiles now preserve their look
/:cl:

floortile type fix

---

code/game/objects/structures/watercloset.dm

fixes showers so that the water overlay gets removed when turned off, as well as making sure you can't keep stacking mist effects by turning it off and on and changes it so that they give a message when turned on/off
bug fix
:cl: dottymint
fix: fixed showers not updating properly
/:cl:

fixes showers

---

code/game/objects/machinery/vending/som_vending.dm

Changes the /improper to be \improper in the SOM weapon rack - as well as changing its name from "SOC weapon rack" to "SOM automated weapons rack" and changing its description to match the marine weapons rack
fixes formatting, changes name and description to be consistent
:cl:
fix: fixed SOM weapons rack formatting, name and description
/:cl:

fixes improper, changes description and name of SOM weapon rack

---

code/modules/food/recipes_processor.dm
tgmc.dme

the food processor had zero recipes for it; this adds raw potato sticks, tortillas, carrot fries, soydope, flour, spaghetti, chocolate bars and raw meatballs
as it stands the food processor doesn't do anything, which is a bit sad
:cl: dottymint
add: some recipes for the food processor (raw potato sticks, tortillas, carrot fries, soydope, flour, spaghetti, chocolate bars and raw meatballs)
/:cl:

food processor fix

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/carbon/xenomorph/embryo.dm
code/modules/mob/mob_verbs.dm

adds a pref "Toggle Burst Screams" using the same implementation as "toggle sex harm" that lets you enable or disable burst screams (however not gagging)
i've seen more than a few people request this and adding a toggle for it seems innocuous enough, makes sense in the context of CLF or otherwise just people who don't want to hear it
:cl: dottymint
add: added a preference for toggling your own burst screams
/:cl:

burst scream pref

---

code/game/objects/machinery/vending/som_vending.dm
code/modules/clothing/modular_armor/xenonauten.dm

pretty much the same as my last pr but this gives the SOM the m10x version of the helmet aswell as the m10 so they can fit all the different armor modules & make use of the dynamic sprites (such as goggles appearing & so on)
the SOM already gets a couple of these in their lockers at roundstart, this way you don't lose out if someone else grabs it as there is a severe lack of decent looking, open faced helmets

stolen m10x for SOM

---

code/datums/components/seethrough_mob.dm

Ports https://github.com/tgstation/TerraGov-Marine-Corps/pull/17023
Fix "Toggle Seethrough" toggle being lost when gaining primo
Bugfix
:cl:
fix: Fix "Toggle Seethrough" toggle being lost when gaining primo
/:cl:

Fix "Toggle Seethrough" toggle being lost when gaining primo

---

code/game/objects/effects/temporary_visuals/miscellaneous.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/update_icons.dm
code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
code/modules/mob/living/living_defense.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/sealed.dm

Ports https://github.com/tgstation/TerraGov-Marine-Corps/pull/17350, https://github.com/tgstation/TerraGov-Marine-Corps/pull/17398 and https://github.com/tgstation/TerraGov-Marine-Corps/pull/17599
Added queen visually warping shriek wave
https://streamable.com/vcwovd
Now screech:
Uses a range define
Uses spatial search instead of hearers
Works on mechs too now
Fixes get dist todo crap
Fixes the in vision range stuff not applying to vehicles
Fixes args not being the same
Fixes the default arg runtiming the proc
It looks badass
:cl:
add: Added queen visually warping shriek wave
refactor: Screech_act refactored, performance improved
fix: Screech now calculates distance from queen for effect correctly instead of just applying the minimum for mech/tank/apc
fix: Screech now considers vehicles …

Improves Queen Screech visuals, refactors it

---

code/game/objects/machinery/vending/som_vending.dm

3x PRTS rifles for the sommites
And unlimited ammo.
Spare the poor martians. They have it bad enough! Let them have some semi-unique weapons to match their style.
:cl:
balance: Sons of Mars now have access to the PTRS rifle.
/:cl:

Gives PTRS to the martians

---

code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/som_vending.dm
code/game/objects/machinery/vending/vending_types.dm

Removes Xenolinguistic Translator from NovaMed Vendor (Advanced Medical Vendor)
Adds Xenolinguistic Translator to MarineMed & SyndiMed Vendor 
Increased amount of Xenolinguistic Translators from 2 to 4
The Xenolinguistic Translators are nice, allows you to have a conversation with multiple xenos a little more easily without the constant need for psychic whispers, and the fact that they're both locked to chem/medical access and limited to only two doesn't seem to match their value (or lack thereof)
It's not a medical item, so shouldn't be gated behind medical access and it doesn't give any real advantage besides potentially being able to listen to xeno chatter if you're near enough. 
I've used these a lot for roleplay value and it's irritating to see them sitting in the vendor that most …

Xenolinguistic Translator Move

---

code/datums/skills.dm

Buffing NTC corpsman skillset, nerfing vanguard's surgery and med skills
Vanguards really do not need med/surgery skills aside from `SKILL_MEDICAL_PRACTICED`, on par with FC's and SO's skill set.
After all, what the vanguards need is the ability to quickly scan an officer's health, inject a couple of drugs to stabilize the body to get them to the medical bay. They don't need a skill set that allows them to operate on the VIP themselves.
Removed Vanguard's proficiency in construction and engineering. They do not need it.
Buffed corpsman skill set to 
```
medical = SKILL_MEDICAL_COMPETENT
surgery = SKILL_SURGERY_PROFESSIONAL
```
NTC gets synths/doctors basically never. Your typical round sees one, maybe two corpsman characters - one of whom is definitely busy scening somewhere. 
:cl: …

RIghting a gross injustice: updating corpsman and vanguard skillset

---

code/modules/projectiles/ammo_types/energy_ammo.dm
code/modules/projectiles/ammo_types/microrail_ammo.dm
code/modules/projectiles/ammo_types/pistol_ammo.dm
code/modules/projectiles/ammo_types/revolver_ammo.dm
code/modules/projectiles/ammo_types/rifle_ammo.dm
code/modules/projectiles/ammo_types/shotgun_ammo.dm
code/modules/projectiles/ammo_types/smg_ammo.dm
code/modules/projectiles/ammo_types/sniper_ammo.dm
code/modules/projectiles/ammo_types/tx54_ammo.dm
code/modules/projectiles/ammo_types/volkite_ammo.dm

This PR is the first of a series of PRs that will be made in an attempt to overhaul HvH and HvX balance to better fit this server as opposed to the current tgmc values.
I have been asked to attempt a weapon rebalance for the majority of the servers firearms. This is due to a number of factors:
**Meta:** Predominantly there are a small pool of meta guns that see far more usage than most other weapons on server, these are predominantly shotguns, in which people utilise the impressive damage alongside the "knockdown" stun slugs provide in order to incapacitate a target. This rebalance project aims to bring other weapons up to par with the current meta, as opposed to simply nerfing the meta entirely. 
**Balance:** The server's balance is still rooted in TGMC, which causes issues for both HvH …

Weapon Rebalance: Part 1

---

code/modules/projectiles/ammo_types/revolver_ammo.dm
code/modules/projectiles/ammo_types/shotgun_ammo.dm

This PR is the second of a series of PRs that will be made in an attempt to overhaul HvH and HvX balance to better fit this server as opposed to the current tgmc values.
I have been asked to attempt a weapon rebalance for the majority of the servers firearms. This is due to a number of factors:
**Meta:** Predominantly there are a small pool of meta guns that see far more usage than most other weapons on server, these are predominantly shotguns, in which people utilise the impressive damage alongside the "knockdown" stun slugs provide in order to incapacitate a target. This rebalance project aims to bring other weapons up to par with the current meta, as opposed to simply nerfing the meta entirely. 
**Balance:** The server's balance is still rooted in TGMC, which causes issues for both HvH …

Weapon Rebalance: Part 1.5

---

code/game/objects/machinery/vending/som_vending.dm

SOM Vendor had the L-88 Assault Carbine but no Magazines in it.
The line for /obj/item/ammo_magazine/rifle/icc_battlecarbine was present twice, instead of the expected /obj/item/ammo_magazine/rifle/icc_assaultcarbine. This is presumed to be in error rather than having two magazines for the same gun. 
SOM were also missing the large variant of their general storage pouches, this has been rectified.
:cl:
fix: Adds the L-88 Assault Carbine mags to SOM vendor
add: Adds the large variant of the general pouch to SOM vendor
/:cl:

Gives L-88 Assault Carbine their Magazines in SOM Vendor (+ Large General Pouches)

---

config/modes.txt

I'm just making it unvotable.
TL;DR - this mode is broken and does not match the preferences of our core audience.
:cl:
config: Zombie crash was disabled.
/:cl:

Removes zombie crash from the pool of votable modes

---

code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/rifles.dm

Replaces CC/77 ext_mag ammo_type and increases AT32 firerate
Those kinda make sense. Check previous weapon adjustment pr if you are looking for reasons of this pr
:cl:
balance: CC/77 Extended magazine now inherits default magazine ammotype
balance: AT32 Fire delay lowered
/:cl:

KZ Weapon Adjustments Part 2

---

code/game/objects/machinery/vending/marine_vending.dm

Adds KZ (VSD) PDW to their vendors under a new SMG listing
Adds the KZ PDW to their Vendor in infinite numbers with the proper ammo also added into the vendor under it's own category.
There was no reason for the SMG to not already be in the vendor as it was not special compared to any of the other weapons and KZ had absolutely no SMGs to pick from, this gives the KZ an additional option to choose from and also gives them at least one SMG to use too.
:cl:
add: KZ PDW to KZ Vendor
add: KZ PDW Magazine to KZ Vendor

KZ PDW Vendor Addition

---

code/__DEFINES/traits.dm
code/_onclick/xeno.dm
code/datums/status_effects/debuffs.dm
code/datums/status_effects/xeno_buffs.dm
code/modules/mob/living/carbon/xenomorph/life.dm

There will be a bit more PRs regarding XvX later on. This one aims to get rid of constant xeno healing, both in crit and fights. If you melee attack a different xeno they will be inflicted with a temporary 10 second debuff that prevents any kind of healing, be it via abilities or natural regen. Castes with high melee defense like Crusher and base King would be able to be killed still since castes with higher speed and range attacks would be able to constantly apply pressure. And other way around, ranged and fast castes would receive more damage since they have lower melee defense and would die faster. Theres also castes with lower slash delay like runner and hunter that can apply constant melee damage despite them not having access to any ranged harassment tools.
XvX is broken. As of now …

Nerf constant xeno healing in XvX

---

code/game/objects/structures/xeno.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Now you can get rid of edible jelly by absorbing it back
Regular resin jelly for example disappears if you apply it on someone. Edible jelly does not. Keep in mind that it gives you nutriments so you can't eat it away if you make too many. But why eat it if you can absorb it back?
:cl:
add: Edible jelly can be absorbed back if activated in hand
/:cl:

Edible jelly can be disposed off

---

code/datums/jobs/job/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/xenomorph/acid_pools.dm
code/modules/xenomorph/maw.dm
code/modules/xenomorph/pherotower.dm
code/modules/xenomorph/recovery_pylon.dm
code/modules/xenomorph/resin_gargoyle.dm
code/modules/xenomorph/silo.dm
code/modules/xenomorph/spawner.dm
code/modules/xenomorph/tunnel.dm
code/modules/xenomorph/xeno_turret.dm

Corrupted can't see normal hive structures anymore as well as normal xenos. Corrupted now can see marines and their structures. Normal hive can't see corrupted hive structures anymore as well as corrupted xenos.
Bugfix
:cl:
fix: Corrupted now properly share their map with marines and not xenos
/:cl:

Fixes corrupted minimap
