EaglePhntm/NTFvsAlien

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
aaaaaaaaa
aaaaaa
:cl:
fix: Last minute damage calculation refactor did an oopsie. It now no longer inversely stacks.
/:cl:
=> Brieeef bugfix

code/modules/reqs/supplypacks.dm
before the PR all factories ended you up with less money, expect pizza, who gave a tiny bit of profit
now all factories give a small bit of profit, additionally pizza giving a little more
additionally, the ntc loot box price was lowered from 1000 to 800
balance doesnt matter much since players arent fighting eachother most of the time either way
ontop of that, setting up factories used to be completely not worth the effort since any factories expect pizza ended up with less money than you paid
this pr makes it so all factories end you up with profit rather than loss
:cl:
tweak: all factory refills are now cheaper
tweak: loot box price 1000 -> 800
/:cl:
=> Buffs cargo's profit rate, lowers lootbox price

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
xenos for unknown reasons had a hard coded multiplier which reduced their stun times by 80%, therefore reducing their stun times drastically and stopping any kind of non-violent takedown
xenos can now be apprehended by security guards properly
:cl:
tweak: /mob/living/carbon/xenomorph/Paralyze Amount *0.2 -> *1
/:cl:
=> Xeno stun fix

code/datums/jobs/job/fallen.dm, code/datums/jobs/job/job.dm, code/datums/jobs/job/terragov.dm, code/modules/admin/topic.dm, code/modules/client/preferences_ui.dm, code/modules/mob/living/carbon/human/human_species.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/mob/new_player/sprite_accessories.dm, code/modules/surgery/headreattach.dm, tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Fixes some minor stuff...Related to preference stuff.
Many thanks to @Zandario for the bulk of the changes made...Hopefully I didn't screw up the changes request on my end, haha.
Fixes good.
:cl: Zandario, Cielo
fix: fixes some character preference things.
/:cl:
=> fixes some stuff related to species.

code/game/objects/items/storage/holsters.dm
Fixed some runtimes.
:cl:
fix: fixed runtimes in holsters.dm
/:cl:
=> Runtime Error Fix: storage_datum

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Fixed component removal. Component autoremoving on `Destroy()`.
:cl:
fix: fixed component removal
/:cl:
=> runtime error fix: /datum/component/xeno_iff

code/datums/elements/strippable.dm
Fix for items going into the void when forcefully dressing people.
Hotfix for being unable to equip items to marines via stripping menu.
Fixing things.
Equip check verified if the person was clothing, not the clothing being clothing.
:cl:
fix: fixed a few things
code: changed some code
=> ForceDressPatch

code/modules/client/preferences_ui.dm
Fixes character creation preview icon sometimes not updating.
Makes it easier to see how things look in character creation, and feels less glitchy.
:cl:
fix: Fixed character creation preview icon sometimes not updating.
/:cl:
=> Fixes character creation preview icon sometimes not updating.

_maps/map_files/NTC_Nine_Tailed_Fox/NTC_Nine_Tailed_Fox.dmm, code/modules/clothing/shoes/miscellaneous.dm, code/modules/clothing/suits/armor.dm
new corpsec office
a few changes to corpsec commander office, removed tranq due to being a bugged weapon
fixed corpsec access being CMO access for some reason, locked corpsec lockers who came unlocked by default for some reason
make HoS's greatcoat now able to equip pistol rigs in its armor slot because it previously couldnt despite getting a pistol rig in his office
HoS's coat now has the same armor values as the beret
prisoners now get plushies
clears a few issues, makes HoS's gear consistent, Marines can no longer walk into brig like they used to be able to, sec lockers are now locked properly like they should be
:cl:
bal: replaced Corpsec commander's tranqualizer rig with a mateba
fix: made Corpsec commander's coat able to equip rigs
del: Removed prisoner hatchets from brig
fix: fixed …
=> Fixes a few issues with corpsec

ntf_modular/code/datums/sexcon/sex_actions/deviant/ear_sex.dm, ntf_modular/code/datums/sexcon/sex_actions/deviant/nipple_sex.dm, ntf_modular/code/datums/sexcon/sex_actions/deviant/thighjob.dm, ntf_modular/code/datums/sexcon/sex_actions/deviant/titjob.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_blowjob.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_crotch_nuzzle.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_foot_lick.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_milk_tits.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_nuzzle_armpit.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_rimming.dm, ntf_modular/code/datums/sexcon/sex_actions/force/force_suck_balls.dm, ntf_modular/code/datums/sexcon/sex_actions/masturbate/masturbate_other_anus.dm, ntf_modular/code/datums/sexcon/sex_actions/masturbate/masturbate_other_breasts.dm, ntf_modular/code/datums/sexcon/sex_actions/masturbate/masturbate_other_vagina.dm, ntf_modular/code/datums/sexcon/sex_actions/masturbate/masturbate_penis_over.dm, ntf_modular/code/datums/sexcon/sex_actions/oral/cunnilingus.dm, ntf_modular/code/datums/sexcon/sex_actions/oral/suck_nipples.dm, ntf_modular/code/datums/sexcon/sex_actions/sex/anal_sex.dm, ntf_modular/code/datums/sexcon/sex_actions/sex/throat_sex.dm
Fixes some erp panel actions being unusable due to missing "return TRUE"s 
Lets people use these actions as intended.
:cl:
fix: fixed some ERP panel actions being unusable.
/:cl:
=> Fixes some erp panel actions

code/datums/components/xeno_iff.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm, code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/xenoattacks.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Make xeno gender affect their pronouns
Looks nicer, reduces confusion about what gender a xeno is supposed to be.
:cl:
add: Made xenos' gender affect their pronouns.
/:cl:
=> Xeno pronouns

code/_onclick/human.dm
Disables tutorials
They're annoying and kinda glitchy.
:cl:
del: Disabled tutorials.
/:cl:
=> Disables tutorials

config/word_filter.toml
Adds "skibidi" to the blocked word filter
Helps preserve the atmosphere.
=> remove skibidi

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Makes facehuggers remove headsets
Helps xenos get captures without starting wars
:cl:
balance: facehuggers now remove headsets
/:cl:
=> Makes facehuggers remove headsets

code/datums/gamemodes/_game_mode.dm, code/datums/round_statistics.dm, code/game/objects/items/implants/implant_items.dm, code/game/objects/items/implants/implanter.dm, code/game/objects/items/implants/sandevistan.dm, code/modules/reqs/supplypacks.dm
Chronos implant 2k
mantis blades 500
jump boost kit 200
:cl:
add: New buyable implants in the imports section on ASRS consoles
/:cl:
=> Implants in cargo

code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/reagents/chemistry/holder/holder.dm
Removed acid from larval sting
Helps captures survive to roleplay with xenos
:cl:
del: Larval sting on uninfested people no long injects acid, only neurotoxin.
/:cl:
=> Improved larval sting

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Makes hivemind eye invisible to humans
It seems like it shouldn't be visible to them, like how ai eye isn't visible to xenos.
:cl:
add: Incorporeal hivemind eyes are now invisible to humans
/:cl:
=> Makes hivemind invisible to humans

code/modules/admin/panels/player_panel.dm, code/modules/admin/topic.dm
Adds toggle for rouny sprites to player panel on xenos
Just saves admins a little time
=> Adds rouny toggle to player panel on xenos

_maps/map_files/NTC_Nine_Tailed_Fox/NTC_Nine_Tailed_Fox.dmm
>be any role
>break into ceo office
>break gear locker
>profit
:cl:
fix: ceo office locker is now indestructable
/:cl:
=> Makes CEO Office Gear locker indestructable

code/modules/reagents/chemistry/reagents/toxin.dm
Neurotoxin only applies a long stun once every 5 minutes, unless removed completely.  Resting or incapacitated marines process large doses of neurotoxin faster.
Neurotoxin seems a bit too strong right now.
:cl:
balance: Neurotoxin only applies a long stun once every 5 minutes, unless removed completely.  Resting or incapacitated marines process large doses of neurotoxin faster.
/:cl:
=> nerf neurotoxin

code/modules/mob/living/carbon/xenomorph/attack_alien.dm
reduces disarm damage a bit
They seem a bit too strong now
:cl:
balance: nerfed xeno disarm damage against humans a bit
/:cl:
=> nerfs disarms

code/game/objects/items/implants/sandevistan.dm
vide said it sucks ass that it immidently damages you a lot and to add a warning for overuse
so i did
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Adjustments to sandevistan

code/game/objects/items/implants/sandevistan.dm
=> fixes a issue with sandevistan being able to infinitely be used by synths since they do not possess a heart

code/datums/storage/subtypes/belt.dm, code/game/objects/items/weapons/stunbaton.dm
Fixes electrified prodder trying to use the wrong icons, making it look broken.
Big "ERROR" icons look bad
:cl:
fix: fixed electrified prodder sprites
/:cl:
=> Fixes prodder icons being broken

code/datums/jobs/job/clf.dm, code/game/objects/items/cards_ids.dm
Gives CLF dogtags
Stops people stealing their ids
=> Gives CLF dogtags

code/controllers/subsystem/vote.dm
As the name says. Non-votes are simply ignored
=> removes default afk continue vote

code/game/objects/machinery/vending/marine_vending.dm
Simply adds the shotgun ammo rig for the VSD Vendor
=> adds shotgun ammo rig to VSD vendor

code/game/verbs/ooc.dm
Lets ghosts use looc
More convenient and useful.
:cl:
add: Ghosts can now use looc
/:cl:
=> Lets ghosts use looc

code/modules/mob/mob.dm
Allows emoting out of bellies
Lets people rp better in bellies
:cl:
add: You can now emote while devoured.
/:cl:
=> Allow emoting out of bellies

code/__HELPERS/logging/_logging.dm
Splits roleplay logging back into individual categories
Makes logs less confusing
:cl:
/:cl:
=> Splits roleplay logging back into individual categories

code/game/verbs/ooc.dm
Fix loocs from bellies being invisible to everyone but the sender
Makes looc more useful
:cl:
fix: Fixed LOOCs sent while devoured not being sent to anyone but the sender.
/:cl:
=> Fix looc from bellies not working

_maps/map_files/LV624/LV624.dmm, _maps/map_files/LV624Small/LV624Small.dmm
=> Replaces SOM patrol base SMES with more practical geothermals.

code/modules/clothing/head/collectable.dm, ntf_modular/code/modules/clothing/head/head.dm
Fixes broken bunny ear and chef hat icons
Broken icons bad
:cl:
/:cl:
=> Fix bunny ear and chef hat icons

code/modules/mob/mob_movement.dm, ntf_modular/code/_DEFINES/ntf_defines.dm, ntf_modular/code/modules/pixel_shift/code/pixel_shift.dm, tgmc.dme
Ports https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175 and https://github.com/Skyrat-SS13/Skyrat-tg/pull/870
People's sprites are no longer locked to a 32x32 grid.
They can also actually lean against walls and stuff now, I guess.
:cl:
add: PIXEL SHIFTING!!!!
/:cl:
=> [SKYRAT PORT] Pixelshifting!

code/modules/clothing/modular_armor/xenonauten.dm
Increases slowdown from 0 to 0.15 (Very Light armor class)
Hey, let's not have 0 slowdown light armor?
:cl:
balance: Bikini armor is no longer weightless and slightly slows you down.
/:cl:
=> Bikini armor rebalance.

code/modules/admin/panels/player_panel.dm, code/modules/admin/topic.dm
Lets admins send disconnected players back to the lobby
Can be useful
:cl:
/:cl:
=> Allow sending disconnected players back to the lobby

code/modules/admin/panels/player_panel.dm, code/modules/admin/topic.dm
Fixes compile errror
Compile errors bad
:cl:
/:cl:
=> Fixes compile errror

code/modules/admin/panels/player_panel.dm
Includes [DC] indicator in player panel for disconnected players.
Conenience, makes it easier to see how many people are actually playing from the player panel
:cl:
/:cl:
=> Player panel [DC] indicator

_maps/map_files/antagmap/antagmap.dmm
Adds some hypersleep chambers/cryo pods to the ICC base
Convenience
:cl:
add: The ICC base now has hypersleep chambers.
/:cl:
=> Gives ICC hypersleep

code/modules/mob/living/say.dm
Doubles the average number of stars in whispers
It seems too easy to understand whispers currently
:cl:
add: Whispers now have twice as many stars on average
/:cl:
=> more stars in whispers

code/datums/datacore.dm
-Fixes PMCs not showing on manifest
-Fixes squad name dividers not showing on manifest
More clear information in manifest.
:cl:
fix: Fixed PMCs not showing on manifest
fix: Fixed squad name dividers not showing on manifest
/:cl:
=> Manifest fixes

code/datums/components/deployable_item.dm
Fix a bug causing sentries to not deploy
It's bad seeing a bunch of undeploy sentries all over the marine ship on spawn.
:cl:
fix: Fixed a bug causing sentries to not deploy.
/:cl:
=> Fix a bug causing sentries to not deploy

code/modules/client/client_procs.dm
Adds a warning about the issues with byond 516.
Helps people figure out the problem.
:cl:
/:cl:
=> Adds a warning about the issues with byond 516

code/datums/quick_load_outfits.dm, code/game/objects/items/storage/belt.dm, code/game/objects/machinery/vending/som_vending.dm
this adds a v-35 loadout for som veterans. Also adds v-35 magazines in limited quantities to som vendors
:)
=> v-35 loadout for som veteran infantryman

code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm, code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
Changes some of the dragon stats and abilities, making it more fair to fight the caste in our typical round.
The dragon can now land off-weeds, is invisible to humans while flying, but takes MUCH longer to land and takes twice as long to take off.
The dragon's breath had it's cooldown doubled, while losing 25% of the damage against grabbed humans.
The dragon is now more vulnerable to explosion damage, making explosives more effective against it.
The dragon is now FASTER, giving it a better chance at chasing humans.
Landing now deals 25% less damage to make it less effective at damaging barricades.
This is all done to make the dragon particularly vulnerable to things like SADAR, grenades, etc. while giving it a better chance at capturing people.
Balance, better compatibility with lower …
=> Dragon Patch

config/config.txt
Triples topic limits
The topic limit messages seem to show up a lot even when people aren't doing anything suspicious.
:cl:
/:cl:
=> Triples topic limits

code/modules/clothing/head/helmet.dm
icc helmets now hide your hair as they're supposed to
=> proper flags for icc helmets

code/world.dm
Trying to find the culprit: day 11.
=> Looop checks

code/game/objects/machinery/computer/intel_computer.dm
Intel computers no longer award points instantly. Instead, they produce a data disk - players have to redeem their points in req.
The disks become uselss after 20 minutes in order to prevent req points hoarding.
This allows more diversified gameplay and increases the amount of interactions between players.
Instead of pressing and forgetting, players will have to actually haul the disks to their ship. Intel computers will become the indended points of interests, allowing for:
- Tensions
- Ambushes
- Conflicts
- Negotiations
- Roleplay
- And more!
:cl:
balance: Intel computers no longer award points instantly. Instead, they produce a data disk - players have to redeem their points in req. Beware, data loses its value after twenty minutes.
/:cl:
=> Intel computers: re-done.

code/__DEFINES/loadout.dm
Adds Stolen Medicament Vendor, Marine F&D Vendor, Engi-Vend to KZ Loadout Vendor Selection
QOL
:cl:
add: Adds Stolen Medicament Vendor, Marine F&D Vendor, Engi-Vend to KZ Loadout Vendor Selection
/:cl:
=> Expands kz loadout vendor list

tgui/packages/tgui/interfaces/PlayerPreferences/index.tsx
=> fixes draw order menu not opening
